#ifndef NUMERICALCONSTANTS
#define NUMERICALCONSTANTS

const int APPLICATION_VK_ID = 4378706;

const int MAX_AUDIO_GET_COUNT = 1000;
const int MAX_ALBUMS_GET_COUNT = 100;

const int DEFAULT_ALBUM_ID = 0;

const int SHORT_STATUS_BAR_MESSAGE = 1000;
const int LONG_STATUS_BAR_MESSAGE = 3000;

#endif // NUMERICALCONSTANTS

