#ifndef NUMERICALCONSTANTS
#define NUMERICALCONSTANTS

const int MAX_AUDIO_GET_COUNT = 6000;
const int SHORT_STATUS_BAR_MESSAGE = 1000;
const int LONG_STATUS_BAR_MESSAGE = 3000;
const int APPLICATION_VK_ID = 4378706;

#endif // NUMERICALCONSTANTS

